### ISSUE TITLE
Add a utility to update AUTHORS.md

### ISSUE THREAD

**Issue by grobie** [prometheus/build_tools#22]
Our authors files are out-of-date in almost all repositories. Due to exactly these reasons, I've never been a fan of such files, users can just use git to request that information.

If we prefer these files, we should have a utility program to extract the list from git and update our files respecting the existing format.

@fabxc @juliusv @brian-brazil @sdurrheimer

**Comment by fabxc** [comment]
Issue with automating is duplication of certain authors (sometimes 5+ times) with different email addresses.

**Comment by sdurrheimer** [comment]
Example script used by docker : https://github.com/docker/docker/blob/master/hack/generate-authors.sh

**Comment by grobie** [comment]
@fabxc sure, but doing that by hand each time is annoying, and I guess we can put the algorithm we're following into code (like taking the first email, or listing all emails comma separated, and/or maintaining a mapping, or ???).

**Comment by grobie** [comment]
@sdurrheimer It would need to not touch an existing maintainers section at the top.

**Comment by grobie** [comment]
We decided to not keep hard-coded authors list in files and maintain a MAINTAINERS.md file instead.
