### ISSUE TITLE
Add a utility to check for license headers

### ISSUE THREAD

**Issue by grobie** [prometheus/build_tools#23]
All repositories need to be checked for license headers. Let's provide the check utility from the prometheus project here.

@fabxc @sdurrheimer

**Comment by fabxc** [comment]
Can/should these sort of things live in promu?

**Comment by sdurrheimer** [comment]
It makes sense to me to add it to promu.

**Comment by grobie** [comment]
Fine with me. In that case should we move this repo to the graveyard and
consolidate everything in promu?

**Comment by grobie** [comment]
Moved to https://github.com/prometheus/promu/issues/58 and done by @beorn7.
